### ISSUE TITLE
Rule: rationale entries in package.json files

### ISSUE THREAD

**Issue by jdhuntington** [microsoft/boll#35]
## What?

For specific sections of `package.json` files, ensure that all dictionary entries have corresponding entries in a `rationale` section.

## Why?

As JSON does not allow comments, it is difficult to annotate tricky or dangerous lines in `package.json` files. Content of certain sections (such as [resolutions](https://classic.yarnpkg.com/en/docs/package-json/#toc-resolutions)) often carry increased risk, and there is a desire to have inline annotations for other developers' benefits.

## Rule specifics

The default configuration of the rule should cause a failure on the following `package.json`
```json
{
  "name": "foo",
  "resolutions": {
    "transitive-package-1": "0.0.29",
  }
}
```
The failure should clarify that "a rationale entry for `resolutions.transitive-package-1` was expected, but was not found".

The default configuration of the rule should succeed on this fixed version of the previous file:
```json
{
  "name": "foo",
  "rationale": {
    "resolutions": {
      "transitive-package-1": "needed because of issue with dependency-package-2",
    }
  },
  "resolutions": {
    "transitive-package-1": "0.0.29",
  }
}
```

`package.json` files that have no need for a `rationale` entry (because of no declared `resolutions` for instance) should succeed as well.

## Configuration options

- `rationaleRequiredList` - a list of keys in `package.json` that require a corresponding entries in `rationale`.
 Default value: `['resolutions', 'workspaces.nohoist']`

**Comment by JasonGore** [comment]
I was going to add a nested case but I see you covered it already with `workspaces.nohoist`. Here are some more examples that I would use today: 
* `syncpack.versionGroups`: This one's actually tricky because it's an array of objects rather than keys we can validate are present in `resolutions`. I'm not sure what the best approach is here.
* `devDependencies` and `dependencies` for certain `package.json` files, like the one in repo root

**Comment by jofrey-a-msft-production** [comment]
#39 Should be fixed with this PR
